# Artificial Neural Network

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataset = pd.read_csv('Bank_data.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
print(y)

[1 0 1 ... 1 1 0]


Label Encoding the "Gender" column

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [6]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

Creating the model and compile it

In [11]:
ann = tf.keras.models.Sequential()

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [14]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [15]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [16]:
#We can create the model with the following code:
# model= tf.keras.models.Sequential([
#                                 tf.keras.layers.Dense(units= 6, activation= 'relu'),
#                                 tf.keras.layers.Dense(units= 6, activation= 'relu'),
#                                 tf.keras.layers.Dense(units= 1, activation='sigmoid')])
# model.compile(...)

In [17]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 455us/step - loss: 0.5252 - accuracy: 0.7880
Epoch 2/100
250/250 [==============================] - 0s 417us/step - loss: 0.4603 - accuracy: 0.7969
Epoch 3/100
250/250 [==============================] - 0s 414us/step - loss: 0.4386 - accuracy: 0.8021
Epoch 4/100
250/250 [==============================] - 0s 420us/step - loss: 0.4255 - accuracy: 0.8084
Epoch 5/100
250/250 [==============================] - 0s 425us/step - loss: 0.4166 - accuracy: 0.8140
Epoch 6/100
250/250 [==============================] - 0s 433us/step - loss: 0.4090 - accuracy: 0.8183
Epoch 7/100
250/250 [==============================] - 0s 403us/step - loss: 0.4017 - accuracy: 0.8198
Epoch 8/100
250/250 [==============================] - 0s 420us/step - loss: 0.3955 - accuracy: 0.8223
Epoch 9/100
250/250 [==============================] - 0s 427us/step - loss: 0.3891 - accuracy: 0.8227
Epoch 10/100
250/250 [==============================] - 0s 411us/step - l

250/250 [==============================] - 0s 440us/step - loss: 0.3377 - accuracy: 0.8650
Epoch 80/100
250/250 [==============================] - 0s 404us/step - loss: 0.3378 - accuracy: 0.8629
Epoch 81/100
250/250 [==============================] - 0s 397us/step - loss: 0.3379 - accuracy: 0.8640
Epoch 82/100
250/250 [==============================] - 0s 407us/step - loss: 0.3377 - accuracy: 0.8644
Epoch 83/100
250/250 [==============================] - 0s 400us/step - loss: 0.3375 - accuracy: 0.8631
Epoch 84/100
250/250 [==============================] - 0s 419us/step - loss: 0.3377 - accuracy: 0.8639
Epoch 85/100
250/250 [==============================] - 0s 400us/step - loss: 0.3372 - accuracy: 0.8637
Epoch 86/100
250/250 [==============================] - 0s 400us/step - loss: 0.3372 - accuracy: 0.8635
Epoch 87/100
250/250 [==============================] - 0s 403us/step - loss: 0.3374 - accuracy: 0.8640
Epoch 88/100
250/250 [==============================] - 0s 395us/step - loss:

### Predicting the result of a single observation

We use the ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [22]:
x_special= scaler.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])
print(ann.predict(x_special), ann.predict(x_special) > 0.5)

[[0.01990762]] [[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

In [19]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1520   75]
 [ 199  206]]


0.863